### ISSUE TITLE
Update for 4.* version

### ISSUE THREAD

**Issue by eckeSolutions** [gesagtgetan/GesagtGetan.KrakenOptimizer#1]
Any chance there will be a update for the 4.* Neos version?

**Comment by gerhard-boden** [comment]
Thanks for the interest in our plugin! 
Just ran some tests and everything seems to be working fine in Neos 4.x. so I just released 2.2.0 with the new version constraint! 

If you run into any trouble feel free to contact us 😃

**Comment by eckeSolutions** [comment]
Thanks for the lightspeed update. Works like a charm :-)
