### ISSUE TITLE
Neos 5.* support

### ISSUE THREAD

**Issue by eckeSolutions** [gesagtgetan/GesagtGetan.KrakenOptimizer#5]
Please update package to support Neos 5.*

**Comment by eckeSolutions** [comment]
Any news?

**Comment by gerhard-boden** [comment]
Hi @eckeSolutions,

sorry for the lack of communication. We talked about this topic internally yesterday and we prioritized, so this will be our first plugin to receive 5.1. support. 

There is also a new implementation on the way (https://github.com/gesagtgetan/GesagtGetan.KrakenOptimizer/pull/3) but we'll update the active one first ofc.

Just out of curiosity: What happens when you manually install this package in your 5.x dev environment? I figured it could just work, but haven't found the time yet to test it out.

**Comment by eckeSolutions** [comment]
Well I really don’t know how to do that, with registering the classes and all that. I am happy to try if you tell me how to do it though.

**Comment by gerhard-boden** [comment]
You could clone the package and run `./flow package:rescan` and it might just work, but to make things easier I created a branch with the correct constraint. Just require this in your root `composer.json`:
`"gesagtgetan/krakenoptimizer": "dev-neos-5-test"`

**Comment by eckeSolutions** [comment]
Adding package (dev-neos-5-test) with composer is currently not possible, since the branch is not showing upon packagist.org (https://packagist.org/packages/gesagtgetan/krakenoptimizer)

Adding the Package manually and using “./flow package:rescan” results in the following error:

> The object "Neos\Flow\Log\SystemLoggerInterface" which was specified as a property in the object configuration of object "GesagtGetan\KrakenOptimizer\Service\ResourceService" (automatically registered class) does not exist. Check for spelling mistakes and if that dependency is correctly configured.
> Type: Neos\Flow\ObjectManagement\Exception\UnknownObjectException
> Code: 1265213849
> File:
> Packages/Framework/Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
> Line: 460

Krakenoptimizer does show up on the package list as “gesagtgetan/krakenoptimizer”

**Comment by gerhard-boden** [comment]
Oh boy, worked for me on Friday because it was updated on our private composer repository, but not the public one (I just set up auto-updates for packagist.org).

Could you please try again, it should at least install just fine now 😊

**Comment by eckeSolutions** [comment]
sorry to bother you again, since requirement is "neos/neos": "^3.0 || ^4.0 || ^5.9"
^5.9 and not 5.0 I still cant install this package. I think its just a typo...

**Comment by gerhard-boden** [comment]
Haha, you're right 🙈  
You don't have to wait until that minor version (which will most probably never come into existence).
I fixed the version constraint

In other good news: @gradinarufelix made great progress on the feature branch with cloud asset support, so we might release that version with support for 5.1 very soon. 

Be aware that the provided test branch for master for 5.x has not been tested for 5.x yet, but should merely provide feedback if some parts work without adjustments.

**Comment by gerhard-boden** [comment]
https://packagist.org/packages/gesagtgetan/krakenoptimizer

Version 3.0.0 is here, sorry for the long wait and special thanks to @gradinarufelix

**Comment by eckeSolutions** [comment]
Thank you verry mutch, this is great!
